# SPDX-FileCopyrightText: 2023 MASH project contributors
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Forgejo systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ forgejo_identifier }}.service"
  register: forgejo_service_stat

- name: Uninstall Forgejo systemd services and files
  when: forgejo_service_stat.stat.exists | bool
  block:
    - name: Ensure Forgejo systemd service is stopped
      ansible.builtin.service:
        name: "{{ forgejo_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Forgejo systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ forgejo_identifier }}.service"
        state: absent

    - name: Ensure Forgejo container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ forgejo_container_network }}"
        state: absent

    - name: Ensure Forgejo container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ forgejo_container_network }}
      register: network_deletion_result
      changed_when: forgejo_container_network in network_deletion_result.stdout

    - name: Ensure Forgejo path does not exist
      ansible.builtin.file:
        path: "{{ forgejo_base_path }}"
        state: absent
